apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ctr-generate-features
  namespace: kubeflow
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: docker.io/yinanli617/ctr-prediction:csv-10000-partitions
  imagePullPolicy: Always
  mainApplicationFile: local:///pipelines/pyspark-ctr.py
  sparkVersion: "3.1.1"
  hadoopConf:
    "fs.gs.project.id": “kfp-yli"
    "fs.gs.system.bucket": “kfp-yli"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/spark-sa.json"
  driver:
    cores: 1
    labels:
      version: 3.1.1
    memory: "1g"
    secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: kfp-yli
    serviceAccount: spark-sa
  executor:
    instances: 2
    cores: 3
    labels:
      version: 3.1.1
    memory: "6g"
    secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: kfp-yli
